cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/helpers/generate.cmake")
set(source "${YARDA_REPOSITORY}/frontend/tests/fixtures/legacy_affine_supported.c")
foreach(mode debug nodebug)
    if(mode STREQUAL "debug")
        set(debug_flag -g)
    else()
        set(debug_flag -g0)
    endif()
    generate_legacy("${mode}" "${source}")
    run_checked("affine hierarchy CLI" "${YARDA_CPP}" ${base} ${diagnostics})
    check_with_oracles("${CMAKE_CURRENT_LIST_DIR}/fixtures/affine.json")
endforeach()
