cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/helpers/generate.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/helpers/json.cmake")
generate_legacy(diagnostics "${CMAKE_CURRENT_LIST_DIR}/fixtures/hierarchy.c")
run_checked("summary without diagnostics" "${YARDA_CPP}" ${base})
configure_file("${result_file}" "${case_dir}/summary.json" COPYONLY)
include("${CMAKE_CURRENT_LIST_DIR}/helpers/hand_result.cmake")
string(JSON analysis_id GET "${payload}" analysis_id)
run_checked("same command repeated" "${YARDA_CPP}" ${base})
compare_files("${result_file}" "${case_dir}/summary.json")
run_checked("telemetry alone" "${YARDA_CPP}" ${base} --telemetry "${telemetry_file}")
compare_files("${result_file}" "${case_dir}/summary.json")

foreach(limit 0 1 11 12 16 17)
    run_checked("events ${limit}" "${YARDA_CPP}" ${base}
        --export-events "${events_file}" --event-limit ${limit})
    compare_files("${result_file}" "${case_dir}/summary.json")
    configure_file("${events_file}" "${case_dir}/events-first.json" COPYONLY)
    run_checked("repeat with telemetry ${limit}" "${YARDA_CPP}" ${base}
        --export-events "${events_file}" --event-limit ${limit}
        --telemetry "${telemetry_file}")
    compare_files("${result_file}" "${case_dir}/summary.json")
    compare_files("${events_file}" "${case_dir}/events-first.json")
    file(READ "${events_file}" payload)
    assert_json("${analysis_id}" analysis_id)
    assert_json("${limit}" event_limit)
    if(limit LESS 16)
        assert_json_length(${limit} events)
        assert_json("ON" events_truncated)
    else()
        assert_json_length(16 events)
        assert_json("OFF" events_truncated)
    endif()
    include("${CMAKE_CURRENT_LIST_DIR}/helpers/hand_events.cmake")
    file(READ "${telemetry_file}" payload)
    assert_json("1" schema_version)
    assert_json("${analysis_id}" analysis_id)
    assert_json("14" source_accesses_emitted)
    assert_json("16" line_references_emitted)
    assert_json("0" maximum_inline_depth)
    assert_json("0" loop_iterations_expanded)
    assert_json_length(6 stage_time_ns)
    foreach(stage parse_lat parse_cache parse_elf resolve_and_stream
                  hierarchy_analysis serialize_result)
        assert_json_type(NUMBER stage_time_ns ${stage})
        string(JSON duration GET "${payload}" stage_time_ns ${stage})
        if(duration LESS 0)
            message(FATAL_ERROR "negative stage duration: ${stage}")
        endif()
    endforeach()
    foreach(field total_time_ns peak_rss_bytes)
        assert_json_type(NUMBER ${field})
    endforeach()
    string(JSON stream GET "${payload}" stage_time_ns resolve_and_stream)
    string(JSON hierarchy GET "${payload}" stage_time_ns hierarchy_analysis)
    string(JSON total GET "${payload}" total_time_ns)
    string(JSON rss GET "${payload}" peak_rss_bytes)
    if(hierarchy GREATER stream OR stream GREATER total OR rss LESS_EQUAL 0)
        message(FATAL_ERROR "invalid timing containment or process RSS")
    endif()
    foreach(field hostname os release machine)
        assert_json_type(STRING host ${field})
        string(JSON value GET "${payload}" host ${field})
        if(value STREQUAL "")
            message(FATAL_ERROR "empty host ${field}")
        endif()
    endforeach()
    string(JSON timestamp GET "${payload}" measured_at_utc)
    if(NOT timestamp MATCHES "^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]Z$")
        message(FATAL_ERROR "invalid UTC timestamp")
    endif()
endforeach()

foreach(kind lat elf)
    configure_file("${${kind}}" "${case_dir}/renamed.${kind}" COPYONLY)
endforeach()
configure_file("${YARDA_CACHE}" "${case_dir}/renamed.yaml" COPYONLY)
run_checked("input and output paths are not identity" "${YARDA_CPP}"
    "${case_dir}/renamed.lat" --analysis hierarchy-rd
    --elf "${case_dir}/renamed.elf" --cache "${case_dir}/renamed.yaml"
    --export "${case_dir}/renamed-result.json")
compare_files("${case_dir}/renamed-result.json" "${case_dir}/summary.json")
