cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/helpers/generate.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/helpers/json.cmake")
set(fixtures "${CMAKE_CURRENT_LIST_DIR}/fixtures")
generate_region(selected "${fixtures}/regions.c")
run_checked("region hierarchy CLI" "${YARDA_CPP}" ${base} ${diagnostics})
check_with_oracles("${fixtures}/regions.json")
file(READ "${telemetry_file}" payload)
assert_json("1" maximum_inline_depth)
assert_json("9" loop_iterations_expanded)
assert_json("18" source_accesses_emitted)
file(READ "${lat}" payload)
string(JSON function_count LENGTH "${payload}" functions)
math(EXPR last_function "${function_count}-1")
set(found OFF)
foreach(index RANGE 0 ${last_function})
    string(JSON name GET "${payload}" functions ${index} function)
    if(name STREQUAL "selected")
        assert_json("region" functions ${index} analysis_scope kind)
        assert_json("APE_ANALYZE" functions ${index} analysis_scope name)
        set(found ON)
    endif()
endforeach()
if(NOT found)
    message(FATAL_ERROR "selected function missing from LAT")
endif()
file(READ "${result_file}" payload)
string(JSON control GET "${payload}" tasks 0)
string(JSON control REMOVE "${control}" task_id)
foreach(task 1 2)
    string(JSON selected GET "${payload}" tasks ${task})
    string(JSON selected REMOVE "${selected}" task_id)
    if(NOT control STREQUAL selected)
        message(FATAL_ERROR "same function/region sources differ in semantics")
    endif()
endforeach()
configure_file("${result_file}" "${case_dir}/first.json" COPYONLY)
run_checked("region rerun" "${YARDA_CPP}" ${base})
compare_files("${result_file}" "${case_dir}/first.json")

file(MAKE_DIRECTORY "${YARDA_WORK_DIR}/sources")
file(READ "${YARDA_REPOSITORY}/frontend/experiments/analysis_regions/fixtures/global_values.c" source)
file(WRITE "${YARDA_WORK_DIR}/sources/global_values.c"
    "${source}\nint main(void) { return 0; }\n")
generate_region(global_values "${YARDA_WORK_DIR}/sources/global_values.c")
run_checked("selected global dependencies" "${YARDA_CPP}" ${base} ${diagnostics})
check_with_oracles("${fixtures}/global_values.json")

generate_region(atax
    "${YARDA_REPOSITORY}/frontend/tests/fixtures/analysis_region_atax.c")
run_checked("small static ATAX hierarchy" "${YARDA_CPP}" ${base} ${diagnostics})
check_with_oracles("${fixtures}/atax.json")
