cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/helpers/generate.cmake")
file(READ "${CMAKE_CURRENT_LIST_DIR}/fixtures/tasks.json" manifest)
string(JSON count LENGTH "${manifest}")
math(EXPR last "${count}-1")
file(MAKE_DIRECTORY "${YARDA_WORK_DIR}/sources")
foreach(index RANGE 0 ${last})
    string(JSON name GET "${manifest}" ${index} source)
    string(JSON golden GET "${manifest}" ${index} golden)
    string(JSON append_main GET "${manifest}" ${index} append_main)
    set(source "${YARDA_REPOSITORY}/tasks/${name}")
    if(append_main)
        file(READ "${source}" body)
        set(source "${YARDA_WORK_DIR}/sources/${name}")
        file(WRITE "${source}" "${body}\nint main(void) { return 0; }\n")
    endif()
    generate_legacy("${name}" "${source}")
    run_checked("task hierarchy regression" "${YARDA_CPP}" ${base} ${diagnostics})
    check_with_oracles("${CMAKE_CURRENT_LIST_DIR}/fixtures/${golden}")
endforeach()
