cmake_minimum_required(VERSION 3.20)

include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")
run_ok(${base})
file(READ "${result_file}" expected)
set(payload "${expected}")
string(JSON analysis_id GET "${payload}" analysis_id)
foreach(limit 0 1 8 9)
    run_ok(${base} --export-events "${events_file}" --event-limit ${limit}
        --telemetry "${telemetry_file}")
    file(READ "${result_file}" actual)
    if(NOT expected STREQUAL actual)
        message(FATAL_ERROR "diagnostics changed RESULT")
    endif()
    file(READ "${events_file}" payload)
    assert_json("${analysis_id}" analysis_id)
    string(JSON count LENGTH "${payload}" events)
    if(limit LESS 8)
        set(retained ${limit})
        assert_json("ON" events_truncated)
    else()
        set(retained 8)
        assert_json("OFF" events_truncated)
    endif()
    if(NOT count EQUAL retained)
        message(FATAL_ERROR "unexpected event prefix length")
    endif()
    if(limit GREATER 0)
        assert_json("first" events 0 task_id)
        assert_json("6291484" events 0 linked_address)
        assert_json("8" events 0 access_size)
        assert_json("Memory" events 0 first_service_level)
    endif()
    file(READ "${telemetry_file}" payload)
    assert_json("${analysis_id}" analysis_id)
    assert_json("4" source_accesses_emitted)
    assert_json("8" line_references_emitted)
    assert_json("4" loop_iterations_expanded)
    foreach(stage parse_map parse_cache parse_elf resolve_and_stream
                  hierarchy_analysis serialize_result)
        string(JSON duration GET "${payload}" stage_time_ns ${stage})
        if(duration LESS 0)
            message(FATAL_ERROR "negative stage time")
        endif()
    endforeach()
    string(JSON stream GET "${payload}" stage_time_ns resolve_and_stream)
    string(JSON hierarchy GET "${payload}" stage_time_ns hierarchy_analysis)
    string(JSON total GET "${payload}" total_time_ns)
    string(JSON rss GET "${payload}" peak_rss_bytes)
    if(hierarchy GREATER stream OR stream GREATER total OR NOT rss GREATER 0)
        message(FATAL_ERROR "invalid telemetry intervals or RSS")
    endif()
endforeach()
run_ok(${base} --export-events "${events_file}")
file(READ "${events_file}" payload)
assert_json("0" event_limit)
