# Source-side errors must preserve LAT and must never reach hierarchy execution.
function(expect_frontend_failure reason)
    foreach(previous absent existing)
        file(REMOVE "${lat}")
        if(previous STREQUAL "existing")
            file(WRITE "${lat}" "previous LAT\n")
        endif()
        execute_process(COMMAND ${ARGN} WORKING_DIRECTORY "${case_dir}"
            RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
        file(APPEND "${case_dir}/commands.log"
            "frontend ${previous}: ${ARGN}\nexit=${status}\n${output}\n${error}\n")
        if(NOT status STREQUAL "1" OR NOT error MATCHES "${reason}")
            message(FATAL_ERROR "expected frontend ${reason}: ${status}\n${error}")
        endif()
        if(previous STREQUAL "existing")
            file(READ "${lat}" retained)
            if(NOT retained STREQUAL "previous LAT\n")
                message(FATAL_ERROR "frontend failure changed LAT")
            endif()
        elseif(EXISTS "${lat}")
            message(FATAL_ERROR "frontend failure published LAT")
        endif()
        foreach(path "${result_file}" "${events_file}" "${telemetry_file}")
            if(EXISTS "${path}")
                message(FATAL_ERROR "frontend rejection left analysis output ${path}")
            endif()
        endforeach()
    endforeach()
endfunction()
