file(READ "${events_file}" payload)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../fixtures/observations.json" observations)
string(JSON count LENGTH "${payload}" events)
if(count GREATER 16)
    message(FATAL_ERROR "extra events beyond the hand trace")
endif()
if(count GREATER 0)
    math(EXPR last "${count}-1")
    foreach(event RANGE 0 ${last})
        foreach(column RANGE 0 9)
            string(JSON field GET "${observations}" columns ${column})
            string(JSON type TYPE "${observations}" rows ${event} ${column})
            if(type STREQUAL "NULL")
                assert_json_type(NULL events ${event} ${field})
            else()
                string(JSON expected GET "${observations}" rows ${event} ${column})
                assert_json("${expected}" events ${event} ${field})
            endif()
        endforeach()
    endforeach()
endif()
